name: Master Branch Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build and Minify
        run:
          npm run build

      - name: Upload Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: build-*
          merge-multiple: true
      
      - name: Commit dist folder
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f dist/
          git commit -m "build: [skip ci]"
          git push